# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/duyngu/Desktop/Project_Graduate/UI/show_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1366, 768)
        Form.setMinimumSize(QtCore.QSize(1366, 768))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        Form.setStyleSheet("background-color: rgb(24, 23, 61)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(10)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Ubuntu\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table_database = QtWidgets.QTableWidget(self.frame)
        self.table_database.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_database.setFrameShape(QtWidgets.QFrame.Box)
        self.table_database.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_database.setLineWidth(5)
        self.table_database.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_database.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_database.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_database.setAutoScroll(True)
        self.table_database.setAutoScrollMargin(16)
        self.table_database.setDragEnabled(False)
        self.table_database.setDragDropOverwriteMode(True)
        self.table_database.setAlternatingRowColors(False)
        self.table_database.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.table_database.setGridStyle(QtCore.Qt.SolidLine)
        self.table_database.setObjectName("table_database")
        self.table_database.setColumnCount(5)
        self.table_database.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.table_database.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_database.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_database.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_database.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_database.setHorizontalHeaderItem(4, item)
        self.table_database.horizontalHeader().setVisible(True)
        self.table_database.horizontalHeader().setCascadingSectionResizes(True)
        self.table_database.horizontalHeader().setDefaultSectionSize(350)
        self.table_database.horizontalHeader().setHighlightSections(True)
        self.table_database.horizontalHeader().setMinimumSectionSize(80)
        self.table_database.horizontalHeader().setSortIndicatorShown(True)
        self.table_database.horizontalHeader().setStretchLastSection(False)
        self.table_database.verticalHeader().setVisible(True)
        self.table_database.verticalHeader().setCascadingSectionResizes(True)
        self.table_database.verticalHeader().setDefaultSectionSize(30)
        self.table_database.verticalHeader().setHighlightSections(False)
        self.table_database.verticalHeader().setSortIndicatorShown(True)
        self.table_database.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table_database)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delete_history = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_history.sizePolicy().hasHeightForWidth())
        self.delete_history.setSizePolicy(sizePolicy)
        self.delete_history.setMinimumSize(QtCore.QSize(150, 50))
        self.delete_history.setMaximumSize(QtCore.QSize(150, 50))
        self.delete_history.setStyleSheet("QPushButton{\n"
"border-color: rgb(255 ,255,255);\n"
"font: 75 15pt \"Ubuntu Condensed\";\n"
"background-color: rgb(136, 138, 133);\n"
"border-width : 1.5px;\n"
"border-style:inset;\n"
"border-radius: 8px;\n"
"padding: 0 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(32, 74, 135);\n"
"\n"
"}")
        self.delete_history.setObjectName("delete_history")
        self.horizontalLayout_4.addWidget(self.delete_history)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "FALL ACTION HISTORY"))
        self.table_database.setSortingEnabled(False)
        item = self.table_database.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_database.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Full Name"))
        item = self.table_database.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Face"))
        item = self.table_database.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Action"))
        item = self.table_database.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Time"))
        self.delete_history.setText(_translate("Form", "DELETE ALL"))
